[config]
schemaVersion = "0.0.1"


[package]
namespace = "FV214Hardiel"
name = "FreeRerollArcanas"
versionNumber = "0.1.2"
description = "Makes your reroll arcanas be free with grasp and give you A LOT of rerolls"
websiteUrl = "https://github.com/FV214Hardiel"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.28"
SGG_Modding-ENVY = "1.1.0"
SGG_Modding-Chalk = "2.0.2"
SGG_Modding-ReLoad = "1.0.1"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", "misc"]
